version: '3.9'

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      DB_URL: postgresql://postgres:postgres@postgredb:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgredb:5432/postgres
      DISCORD_CLIENT_ID: test
      DISCORD_CLIENT_SECRET: test
      NODE_ENV: test
    depends_on:
      - postgredb
  postgredb:
    container_name: postgredb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}